//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace A_journey_through_miniature_Uzhhorod.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("A_journey_through_miniature_Uzhhorod.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ваш обліковий запис заблоковано..
        /// </summary>
        public static string AccountBlocked {
            get {
                return ResourceManager.GetString("AccountBlocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ви впевнені, що хочете видалити свій акаунт?.
        /// </summary>
        public static string AccountDelete {
            get {
                return ResourceManager.GetString("AccountDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Акаунт видалено успішно..
        /// </summary>
        public static string AccountDeleted {
            get {
                return ResourceManager.GetString("AccountDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дії.
        /// </summary>
        public static string Actions {
            get {
                return ResourceManager.GetString("Actions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Активні.
        /// </summary>
        public static string Active {
            get {
                return ResourceManager.GetString("Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Активності.
        /// </summary>
        public static string Activities {
            get {
                return ResourceManager.GetString("Activities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Історія.
        /// </summary>
        public static string Activity {
            get {
                return ResourceManager.GetString("Activity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Додати подію.
        /// </summary>
        public static string AddEvent {
            get {
                return ResourceManager.GetString("AddEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Скульптуру додано до улюблених..
        /// </summary>
        public static string AddFavorite {
            get {
                return ResourceManager.GetString("AddFavorite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Додати скульптурку.
        /// </summary>
        public static string AddSculpture {
            get {
                return ResourceManager.GetString("AddSculpture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Відповідь адміністратора.
        /// </summary>
        public static string AdminResponse {
            get {
                return ResourceManager.GetString("AdminResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Усі відгуки успішно видалено!.
        /// </summary>
        public static string AllReviewsRemoved {
            get {
                return ResourceManager.GetString("AllReviewsRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вже є аккаунт?.
        /// </summary>
        public static string AlreadyHaveAnAccount {
            get {
                return ResourceManager.GetString("AlreadyHaveAnAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Відгуків ще немає..
        /// </summary>
        public static string AnavaibleReviews {
            get {
                return ResourceManager.GetString("AnavaibleReviews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Авторизація.
        /// </summary>
        public static string AuthorizationTitle {
            get {
                return ResourceManager.GetString("AuthorizationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Авторизація успішна!.
        /// </summary>
        public static string AuthSuccessful {
            get {
                return ResourceManager.GetString("AuthSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Натисніть для зміни аватару.
        /// </summary>
        public static string AvatarButtonToolTip {
            get {
                return ResourceManager.GetString("AvatarButtonToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Заблоковані.
        /// </summary>
        public static string Blocked {
            get {
                return ResourceManager.GetString("Blocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Переглянути 3D Модель.
        /// </summary>
        public static string Button3DModel {
            get {
                return ResourceManager.GetString("Button3DModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Додати або видалити з улюблених.
        /// </summary>
        public static string ButtonAddFavoriteToolTip {
            get {
                return ResourceManager.GetString("ButtonAddFavoriteToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Назад.
        /// </summary>
        public static string ButtonBackToolTip {
            get {
                return ResourceManager.GetString("ButtonBackToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Очистити маршрут.
        /// </summary>
        public static string ButtonClearRoute {
            get {
                return ResourceManager.GetString("ButtonClearRoute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вийти.
        /// </summary>
        public static string ButtonExit {
            get {
                return ResourceManager.GetString("ButtonExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Переглянути улюблені.
        /// </summary>
        public static string ButtonFavoriteToolTip {
            get {
                return ResourceManager.GetString("ButtonFavoriteToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to РЕЄСТРАЦІЯ.
        /// </summary>
        public static string ButtonRegistry {
            get {
                return ResourceManager.GetString("ButtonRegistry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Прокласти маршрут.
        /// </summary>
        public static string ButtonRoute {
            get {
                return ResourceManager.GetString("ButtonRoute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Зберегти.
        /// </summary>
        public static string ButtonSave {
            get {
                return ResourceManager.GetString("ButtonSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Надіслати.
        /// </summary>
        public static string ButtonSendFeedBack {
            get {
                return ResourceManager.GetString("ButtonSendFeedBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Перейти до застосунку.
        /// </summary>
        public static string ButtonToProgram {
            get {
                return ResourceManager.GetString("ButtonToProgram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Скасувати.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Категорія.
        /// </summary>
        public static string Category {
            get {
                return ResourceManager.GetString("Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Змінити модель.
        /// </summary>
        public static string Change3DModel {
            get {
                return ResourceManager.GetString("Change3DModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Змінити роль.
        /// </summary>
        public static string ChangeRole {
            get {
                return ResourceManager.GetString("ChangeRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Змінити статус.
        /// </summary>
        public static string ChangeStatus {
            get {
                return ResourceManager.GetString("ChangeStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Виберіть скульптурку!.
        /// </summary>
        public static string ChooseSculpture {
            get {
                return ResourceManager.GetString("ChooseSculpture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ви впевнені, що хочете очистити історію?.
        /// </summary>
        public static string ClearHistory {
            get {
                return ResourceManager.GetString("ClearHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ви впевнені, що хочете видалити запис?.
        /// </summary>
        public static string ClearRecord {
            get {
                return ResourceManager.GetString("ClearRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Код підтвердження надіслано на.
        /// </summary>
        public static string CodeSent {
            get {
                return ResourceManager.GetString("CodeSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete the message?.
        /// </summary>
        public static string DeleteFeedback {
            get {
                return ResourceManager.GetString("DeleteFeedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ви впевнені, що хочете видалити відгук?.
        /// </summary>
        public static string DeleteReview {
            get {
                return ResourceManager.GetString("DeleteReview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Опис.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ще немає аккаунту?.
        /// </summary>
        public static string DontHaveAcount {
            get {
                return ResourceManager.GetString("DontHaveAcount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ви знайшли секретного потужного випускника нашого коледжу.
        /// </summary>
        public static string EasterEgg {
            get {
                return ResourceManager.GetString("EasterEgg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Електронна адреса.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Користувач із таким email вже існує..
        /// </summary>
        public static string EmailAlredyExist {
            get {
                return ResourceManager.GetString("EmailAlredyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Приклад: ВашаАдреса@gmail.com.
        /// </summary>
        public static string EmailToolTip {
            get {
                return ResourceManager.GetString("EmailToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введіть код, надісланий на вашу електронну пошту:.
        /// </summary>
        public static string EnterCode {
            get {
                return ResourceManager.GetString("EnterCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введіть коментар!.
        /// </summary>
        public static string EnterComment {
            get {
                return ResourceManager.GetString("EnterComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Для зміни пароля введіть старий пароль!.
        /// </summary>
        public static string EnterOldPassword {
            get {
                return ResourceManager.GetString("EnterOldPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ❌ Помилка видалення акаунту..
        /// </summary>
        public static string ErrorAccountDelete {
            get {
                return ResourceManager.GetString("ErrorAccountDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Помилка надсилання листа: .
        /// </summary>
        public static string ErrorSendingMail {
            get {
                return ResourceManager.GetString("ErrorSendingMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Помилка при збереженні: .
        /// </summary>
        public static string ErrorWhileSaving {
            get {
                return ResourceManager.GetString("ErrorWhileSaving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата події: .
        /// </summary>
        public static string EventDate {
            get {
                return ResourceManager.GetString("EventDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ви дійсно бажаєте видалити цю подію?.
        /// </summary>
        public static string EventDelete {
            get {
                return ResourceManager.GetString("EventDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Подію збережено успішно!.
        /// </summary>
        public static string EventSave {
            get {
                return ResourceManager.GetString("EventSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Виберіть дату події..
        /// </summary>
        public static string EventsDate {
            get {
                return ResourceManager.GetString("EventsDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Усі поля заголовку та опису обов&apos;язкові для обох мов..
        /// </summary>
        public static string EventsValidation {
            get {
                return ResourceManager.GetString("EventsValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Для пошуку введіть назву або дату.
        /// </summary>
        public static string EventTextBoxSearchToolTip {
            get {
                return ResourceManager.GetString("EventTextBoxSearchToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Зворотній зв&apos;язок.
        /// </summary>
        public static string Feedback {
            get {
                return ResourceManager.GetString("Feedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Помилка.
        /// </summary>
        public static string FeedbackCategoryError {
            get {
                return ResourceManager.GetString("FeedbackCategoryError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Інше.
        /// </summary>
        public static string FeedbackCategoryOther {
            get {
                return ResourceManager.GetString("FeedbackCategoryOther", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пропозиція.
        /// </summary>
        public static string FeedbackCategorySuggestion {
            get {
                return ResourceManager.GetString("FeedbackCategorySuggestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введіть повідомлення..
        /// </summary>
        public static string FeedbackEnterMessage {
            get {
                return ResourceManager.GetString("FeedbackEnterMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Повідомлення видалено успішно.
        /// </summary>
        public static string FeedbackRemoved {
            get {
                return ResourceManager.GetString("FeedbackRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Оберіть категорію..
        /// </summary>
        public static string FeedbackSelectCategory {
            get {
                return ResourceManager.GetString("FeedbackSelectCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дякуємо за ваш зворотній зв&apos;язок!.
        /// </summary>
        public static string FeedbackSuccessMessage {
            get {
                return ResourceManager.GetString("FeedbackSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Файл збережено успішно! .
        /// </summary>
        public static string FileSavedSuccessfully {
            get {
                return ResourceManager.GetString("FileSavedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Будь ласка, заповніть усі поля!.
        /// </summary>
        public static string FillAllFields {
            get {
                return ResourceManager.GetString("FillAllFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Будь ласка, заповніть усі поля!.
        /// </summary>
        public static string FillAllFieldsMessage {
            get {
                return ResourceManager.GetString("FillAllFieldsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Досягнення.
        /// </summary>
        public static string Filter_Achievement {
            get {
                return ResourceManager.GetString("Filter_Achievement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Всі.
        /// </summary>
        public static string Filter_All {
            get {
                return ResourceManager.GetString("Filter_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Виконані .
        /// </summary>
        public static string Filter_Completed {
            get {
                return ResourceManager.GetString("Filter_Completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Невиконані .
        /// </summary>
        public static string Filter_Incomplete {
            get {
                return ResourceManager.GetString("Filter_Incomplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Квест.
        /// </summary>
        public static string Filter_Quest {
            get {
                return ResourceManager.GetString("Filter_Quest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Оцінювання.
        /// </summary>
        public static string Filter_Rating {
            get {
                return ResourceManager.GetString("Filter_Rating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Відгук.
        /// </summary>
        public static string Filter_Review {
            get {
                return ResourceManager.GetString("Filter_Review", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Перегляд.
        /// </summary>
        public static string Filter_View {
            get {
                return ResourceManager.GetString("Filter_View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Звідки.
        /// </summary>
        public static string From_where {
            get {
                return ResourceManager.GetString("From where", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата.
        /// </summary>
        public static string HomeDateEvents {
            get {
                return ResourceManager.GetString("HomeDateEvents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Цікава подія:.
        /// </summary>
        public static string HomeTitleEvents {
            get {
                return ResourceManager.GetString("HomeTitleEvents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ПОПУЛЯРНІ МІНІАТЮРИ:.
        /// </summary>
        public static string HomeTitleSculptures {
            get {
                return ResourceManager.GetString("HomeTitleSculptures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Натисніть, щоб змінити зображення.
        /// </summary>
        public static string ImageChange {
            get {
                return ResourceManager.GetString("ImageChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введено некоректний формат електронної пошти!.
        /// </summary>
        public static string IncorrectEmailFormat {
            get {
                return ResourceManager.GetString("IncorrectEmailFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Неправильний старий пароль!.
        /// </summary>
        public static string IncorrectOldPassword {
            get {
                return ResourceManager.GetString("IncorrectOldPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Невірний код підтвердження! Реєстрацію скасовано..
        /// </summary>
        public static string InvalidCode {
            get {
                return ResourceManager.GetString("InvalidCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Невірний код підтвердження. Видалення скасовано..
        /// </summary>
        public static string InvalidCodeDelete {
            get {
                return ResourceManager.GetString("InvalidCodeDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Останні повідомлення.
        /// </summary>
        public static string LatestMessages {
            get {
                return ResourceManager.GetString("LatestMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to УВІЙТИ.
        /// </summary>
        public static string LoginButton {
            get {
                return ResourceManager.GetString("LoginButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ви хочете вийти з аккаунту?.
        /// </summary>
        public static string LogOut {
            get {
                return ResourceManager.GetString("LogOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Натисніть для зміни мови.
        /// </summary>
        public static string MainLanguageToolTip {
            get {
                return ResourceManager.GetString("MainLanguageToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Головне меню.
        /// </summary>
        public static string MainMenu {
            get {
                return ResourceManager.GetString("MainMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Натисніть щоб увійти.
        /// </summary>
        public static string MainTextBlockUserName {
            get {
                return ResourceManager.GetString("MainTextBlockUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Помилка завантаження маркерів: .
        /// </summary>
        public static string MarkerError {
            get {
                return ResourceManager.GetString("MarkerError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Мандрівка мініатюрним Ужгородом.
        /// </summary>
        public static string Menu_title {
            get {
                return ResourceManager.GetString("Menu_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Повідомлення.
        /// </summary>
        public static string Message {
            get {
                return ResourceManager.GetString("Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Залишити відгук.
        /// </summary>
        public static string MiniatureButtonAddReview {
            get {
                return ResourceManager.GetString("MiniatureButtonAddReview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Мініатюри.
        /// </summary>
        public static string Miniatures {
            get {
                return ResourceManager.GetString("Miniatures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ваш відгук:.
        /// </summary>
        public static string MiniatureTextBlockAddReview {
            get {
                return ResourceManager.GetString("MiniatureTextBlockAddReview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Оцініть скульптурку:.
        /// </summary>
        public static string MiniatureTextBlockRate {
            get {
                return ResourceManager.GetString("MiniatureTextBlockRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Рейтинг: .
        /// </summary>
        public static string MiniatureTextBlockRating {
            get {
                return ResourceManager.GetString("MiniatureTextBlockRating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Відгуки:.
        /// </summary>
        public static string MiniatureTextBlockReview {
            get {
                return ResourceManager.GetString("MiniatureTextBlockReview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3D-модель для цієї скульптурки відсутня..
        /// </summary>
        public static string ModelAnavaible {
            get {
                return ResourceManager.GetString("ModelAnavaible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Наступна.
        /// </summary>
        public static string NextPageToolTip {
            get {
                return ResourceManager.GetString("NextPageToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ні.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Немає повідомлень.
        /// </summary>
        public static string NoMessage {
            get {
                return ResourceManager.GetString("NoMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Користувачів ще немає.
        /// </summary>
        public static string NoUsers {
            get {
                return ResourceManager.GetString("NoUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пароль.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Мінімум 8 символів. Принаймні одна велика англійська літера. Принаймні одна мала англійська літера.&amp;#x0a;Принаймні одна цифра. Принаймні один спеціальний символ..
        /// </summary>
        public static string PasswordToolTip {
            get {
                return ResourceManager.GetString("PasswordToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пароль має бути не менше 6 символів, хоча б одну літеру та цифру..
        /// </summary>
        public static string PasswordValidation {
            get {
                return ResourceManager.GetString("PasswordValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Очистити все.
        /// </summary>
        public static string PersonalOfficeButtonClearHistory {
            get {
                return ResourceManager.GetString("PersonalOfficeButtonClearHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Очистити всі.
        /// </summary>
        public static string PersonalOfficeButtonClearReviews {
            get {
                return ResourceManager.GetString("PersonalOfficeButtonClearReviews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Видалити.
        /// </summary>
        public static string PersonalOfficeButtonDelete {
            get {
                return ResourceManager.GetString("PersonalOfficeButtonDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Натисніть щоб видалити.
        /// </summary>
        public static string PersonalOfficeButtonDeleteFeedback {
            get {
                return ResourceManager.GetString("PersonalOfficeButtonDeleteFeedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Видалити запис.
        /// </summary>
        public static string PersonalOfficeButtonDeleteRecord {
            get {
                return ResourceManager.GetString("PersonalOfficeButtonDeleteRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Видалити відгук.
        /// </summary>
        public static string PersonalOfficeButtonDeleteReview {
            get {
                return ResourceManager.GetString("PersonalOfficeButtonDeleteReview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вийти.
        /// </summary>
        public static string PersonalOfficeButtonLeave {
            get {
                return ResourceManager.GetString("PersonalOfficeButtonLeave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Зберегти зміни.
        /// </summary>
        public static string PersonalOfficeButtonSave {
            get {
                return ResourceManager.GetString("PersonalOfficeButtonSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Очистити відгуки.
        /// </summary>
        public static string PersonalOfficeClearReviewsToolTip {
            get {
                return ResourceManager.GetString("PersonalOfficeClearReviewsToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ще немає повідомленнь.
        /// </summary>
        public static string PersonalOfficeDontHaveFeedbacks {
            get {
                return ResourceManager.GetString("PersonalOfficeDontHaveFeedbacks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Історія дій ще порожня.
        /// </summary>
        public static string PersonalOfficeDontHaveHistory {
            get {
                return ResourceManager.GetString("PersonalOfficeDontHaveHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to У вас ще немає відгуків.
        /// </summary>
        public static string PersonalOfficeDontHaveReviews {
            get {
                return ResourceManager.GetString("PersonalOfficeDontHaveReviews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Редагування даних.
        /// </summary>
        public static string PersonalOfficeEditTitle {
            get {
                return ResourceManager.GetString("PersonalOfficeEditTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ваші повідомлення.
        /// </summary>
        public static string PersonalOfficeFeedbackTitle {
            get {
                return ResourceManager.GetString("PersonalOfficeFeedbackTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Інформація.
        /// </summary>
        public static string PersonalOfficeInfoTitle {
            get {
                return ResourceManager.GetString("PersonalOfficeInfoTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Новий пароль.
        /// </summary>
        public static string PersonalOfficeNewPassword {
            get {
                return ResourceManager.GetString("PersonalOfficeNewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Старий пароль.
        /// </summary>
        public static string PersonalOfficeOldPassword {
            get {
                return ResourceManager.GetString("PersonalOfficeOldPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Історія дій:.
        /// </summary>
        public static string PersonalOfficeTextBlockHistoryTitle {
            get {
                return ResourceManager.GetString("PersonalOfficeTextBlockHistoryTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Оцінка: .
        /// </summary>
        public static string PersonalOfficeTextBlockRate {
            get {
                return ResourceManager.GetString("PersonalOfficeTextBlockRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ваші відгуки:.
        /// </summary>
        public static string PersonalOfficeYourReviews {
            get {
                return ResourceManager.GetString("PersonalOfficeYourReviews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Очистити історію дій.
        /// </summary>
        public static string POButtonClearHistoryToolTip {
            get {
                return ResourceManager.GetString("POButtonClearHistoryToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Невірний код підтвердження! Зміни не збережено..
        /// </summary>
        public static string POInvalidCode {
            get {
                return ResourceManager.GetString("POInvalidCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Попередня.
        /// </summary>
        public static string PrewPageToolTip {
            get {
                return ResourceManager.GetString("PrewPageToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Профіль оновлено успішно!.
        /// </summary>
        public static string ProfileUpdated {
            get {
                return ResourceManager.GetString("ProfileUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ви впевнені, що хочете вийти з акаунту?.
        /// </summary>
        public static string QuestionLogOut {
            get {
                return ResourceManager.GetString("QuestionLogOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Головна.
        /// </summary>
        public static string RadioButton_Home {
            get {
                return ResourceManager.GetString("RadioButton_Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Досягнення.
        /// </summary>
        public static string RadioButtonAchievement {
            get {
                return ResourceManager.GetString("RadioButtonAchievement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Редагування досягнень.
        /// </summary>
        public static string RadioButtonEditAchievment {
            get {
                return ResourceManager.GetString("RadioButtonEditAchievment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Редагування подій.
        /// </summary>
        public static string RadioButtonEditEvents {
            get {
                return ResourceManager.GetString("RadioButtonEditEvents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Редагування допомоги.
        /// </summary>
        public static string RadioButtonEditHelp {
            get {
                return ResourceManager.GetString("RadioButtonEditHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Редагування квестів.
        /// </summary>
        public static string RadioButtonEditQuest {
            get {
                return ResourceManager.GetString("RadioButtonEditQuest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Редагування скульптурок.
        /// </summary>
        public static string RadioButtonEditSculpture {
            get {
                return ResourceManager.GetString("RadioButtonEditSculpture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Користувачі.
        /// </summary>
        public static string RadioButtonEditUsers {
            get {
                return ResourceManager.GetString("RadioButtonEditUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Події.
        /// </summary>
        public static string RadioButtonEvents {
            get {
                return ResourceManager.GetString("RadioButtonEvents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Зворотній зв&apos;язок.
        /// </summary>
        public static string RadioButtonFeedback {
            get {
                return ResourceManager.GetString("RadioButtonFeedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Допомога в користуванні.
        /// </summary>
        public static string RadioButtonHelp {
            get {
                return ResourceManager.GetString("RadioButtonHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Мапа розташування.
        /// </summary>
        public static string RadioButtonMap {
            get {
                return ResourceManager.GetString("RadioButtonMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Список скульптурок.
        /// </summary>
        public static string RadioButtonMiniatures {
            get {
                return ResourceManager.GetString("RadioButtonMiniatures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Особистий кабінет.
        /// </summary>
        public static string RadioButtonPersonalOffice {
            get {
                return ResourceManager.GetString("RadioButtonPersonalOffice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Квести.
        /// </summary>
        public static string RadioButtonQuest {
            get {
                return ResourceManager.GetString("RadioButtonQuest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата: .
        /// </summary>
        public static string RandomEventDate {
            get {
                return ResourceManager.GetString("RandomEventDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ваша оцінка оновлена до .
        /// </summary>
        public static string RatingUpdate {
            get {
                return ResourceManager.GetString("RatingUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Запис видалено!.
        /// </summary>
        public static string RecordRemoved {
            get {
                return ResourceManager.GetString("RecordRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Реєстрація.
        /// </summary>
        public static string Registration {
            get {
                return ResourceManager.GetString("Registration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Спочатку зареєструйтесь або увійдіть у профіль..
        /// </summary>
        public static string RegOrLogProfile {
            get {
                return ResourceManager.GetString("RegOrLogProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Реєстрація успішна!.
        /// </summary>
        public static string RegSuccsesfully {
            get {
                return ResourceManager.GetString("RegSuccsesfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Скульптуру вилучено з улюблених..
        /// </summary>
        public static string RemoveFavorite {
            get {
                return ResourceManager.GetString("RemoveFavorite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ви впевнені, що хочете очистити відгуки?.
        /// </summary>
        public static string RemoveReviews {
            get {
                return ResourceManager.GetString("RemoveReviews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Відгук видалено!.
        /// </summary>
        public static string ReviewRemoved {
            get {
                return ResourceManager.GetString("ReviewRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Відгуки.
        /// </summary>
        public static string Reviews {
            get {
                return ResourceManager.GetString("Reviews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ваш відгук збережено!.
        /// </summary>
        public static string ReviewSaved {
            get {
                return ResourceManager.GetString("ReviewSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Роль.
        /// </summary>
        public static string Role {
            get {
                return ResourceManager.GetString("Role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  збережена!.
        /// </summary>
        public static string Saved {
            get {
                return ResourceManager.GetString("Saved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Збереження....
        /// </summary>
        public static string Saving {
            get {
                return ResourceManager.GetString("Saving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Опис скульптурки.
        /// </summary>
        public static string SculptureDescription {
            get {
                return ResourceManager.GetString("SculptureDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Натисніть щоб відкрити детальніше.
        /// </summary>
        public static string SculptureDetailOpen {
            get {
                return ResourceManager.GetString("SculptureDetailOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Назва скульптурки.
        /// </summary>
        public static string SculptureName {
            get {
                return ResourceManager.GetString("SculptureName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Оберіть обидві мініатюри..
        /// </summary>
        public static string SelectBothSculptures {
            get {
                return ResourceManager.GetString("SelectBothSculptures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Статус.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Оберіть категорію.
        /// </summary>
        public static string TextBlockKategoryFeedBack {
            get {
                return ResourceManager.GetString("TextBlockKategoryFeedBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Широта:.
        /// </summary>
        public static string TextBlockLatitude {
            get {
                return ResourceManager.GetString("TextBlockLatitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Довгота:.
        /// </summary>
        public static string TextBlockLongitude {
            get {
                return ResourceManager.GetString("TextBlockLongitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Напишіть повідомлення.
        /// </summary>
        public static string TextBlockMessageFeedBack {
            get {
                return ResourceManager.GetString("TextBlockMessageFeedBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Заблоковано.
        /// </summary>
        public static string TextBlockQuestBlocked {
            get {
                return ResourceManager.GetString("TextBlockQuestBlocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Відцентрувати.
        /// </summary>
        public static string TextBlockQuestCenter {
            get {
                return ResourceManager.GetString("TextBlockQuestCenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Виконано.
        /// </summary>
        public static string TextBlockQuestDone {
            get {
                return ResourceManager.GetString("TextBlockQuestDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to У процесі.
        /// </summary>
        public static string TextBlockQuestInProcess {
            get {
                return ResourceManager.GetString("TextBlockQuestInProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Масштаб:.
        /// </summary>
        public static string TextBlockQuestScale {
            get {
                return ResourceManager.GetString("TextBlockQuestScale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Оцінка: .
        /// </summary>
        public static string TextBlockReviewRate {
            get {
                return ResourceManager.GetString("TextBlockReviewRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Будь-яке повідомлення.
        /// </summary>
        public static string TextBoxMessageFeedBackToolTip {
            get {
                return ResourceManager.GetString("TextBoxMessageFeedBackToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Для пошуку введіть назву.
        /// </summary>
        public static string TextBoxSearchToolTip {
            get {
                return ResourceManager.GetString("TextBoxSearchToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Заголовок.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Загальна кількість скульптур:.
        /// </summary>
        public static string TotalMiniatures {
            get {
                return ResourceManager.GetString("TotalMiniatures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Куди.
        /// </summary>
        public static string ToWhere {
            get {
                return ResourceManager.GetString("ToWhere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Невірний нікнейм або пароль.
        /// </summary>
        public static string UnfaithfulUsernameOrPassword {
            get {
                return ResourceManager.GetString("UnfaithfulUsernameOrPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Помилка оновлення маркерів: .
        /// </summary>
        public static string UpdateMarkers {
            get {
                return ResourceManager.GetString("UpdateMarkers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Користувач.
        /// </summary>
        public static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iм&apos;я користувача.
        /// </summary>
        public static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Це ім&apos;я уже зайняте!.
        /// </summary>
        public static string UsernameTaken {
            get {
                return ResourceManager.GetString("UsernameTaken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Літери або цифри.
        /// </summary>
        public static string UsernameToolTip {
            get {
                return ResourceManager.GetString("UsernameToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ім&apos;я має мати від 3 до 20 символів і складатися з літер, цифр або &apos;_&apos;..
        /// </summary>
        public static string UsernameValidation {
            get {
                return ResourceManager.GetString("UsernameValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Користувача не знайдено!.
        /// </summary>
        public static string UserNotFound {
            get {
                return ResourceManager.GetString("UserNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Користувачі.
        /// </summary>
        public static string Users {
            get {
                return ResourceManager.GetString("Users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Перевірити.
        /// </summary>
        public static string Verify {
            get {
                return ResourceManager.GetString("Verify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Мандрівка мініатюрним Ужгородом.
        /// </summary>
        public static string WelcomeTitle {
            get {
                return ResourceManager.GetString("WelcomeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Так.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ваша оцінка .
        /// </summary>
        public static string YourRating {
            get {
                return ResourceManager.GetString("YourRating", resourceCulture);
            }
        }
    }
}
